
spring.cloud.aws.region.static=us-east-2

# LocalStack overrides for AWS clients/resources
spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test

spring.cloud.aws.s3.endpoint=http://localhost:4566
spring.cloud.aws.s3.path-style-access-enabled=true
spring.cloud.aws.sqs.endpoint=http://localhost:4566
spring.cloud.aws.ses.endpoint=http://localhost:4566

aws.document-bucket=local-andd3dfx-backend-document-s3
aws.email-configuration-set-name=local_TlsConfigurationSet

aws.something1-queue=local_Something1Queue
aws.something2-queue=local_Something2Queue
aws.send-mail-queue=local_SendMailQueue

sender.email-address=test-local@andd3dfx-company.com
